(() => {
  const D={
    th:{home:'หน้าหลัก',apply:'สมัคร',pay:'ชำระเงิน',form:'ฟอร์มสมัคร',status:'ตรวจสอบสถานะ',open:'เปิดรับสมัคร',closed:'ปิดรับสมัคร',fee:'ค่าสมัคร',unlimited:'รับสมัครไม่จำกัดจำนวน',choose:'เลือกประเภทการแข่งขัน',payTitle:'ชำระค่าสมัคร',payHelp:'สแกน PromptPay QR Code แล้วบันทึกสลิปไว้',paid:'ชำระเงินแล้ว • ไปกรอกใบสมัคร',amount:'ยอดชำระ',baht:'บาท',applicant:'ข้อมูลผู้สมัคร',docType:'ประเภทเอกสาร',thaiId:'บัตรประชาชนไทย',passport:'Passport',first:'ชื่อ',last:'นามสกุล',dob:'วันเกิด',phone:'เบอร์โทรศัพท์',email:'อีเมล',emergency:'ผู้ติดต่อฉุกเฉิน',emergencyPhone:'เบอร์โทรฉุกเฉิน',category:'ประเภทการแข่งขัน',slip:'สลิปการชำระเงิน',verifySlip:'ตรวจสอบสลิป',checking:'กำลังตรวจสอบสลิป...',verified:'ตรวจสอบสลิปสำเร็จ',submit:'ยืนยันการสมัคร',terms:'ยืนยันว่าข้อมูลถูกต้องและยอมรับเงื่อนไข',success:'สมัครสำเร็จ',waiting:'กำลังบันทึกข้อมูล...',required:'กรุณากรอกข้อมูลให้ครบ',invalidThai:'เลขบัตรประชาชนไม่ถูกต้อง',invalidPassport:'เลข Passport ไม่อยู่ในรูปแบบที่กำหนด',slipRequired:'ต้องตรวจสอบสลิปให้ผ่านก่อน',back:'กลับหน้าหลัก',lang:'ภาษา'},
    en:{home:'Home',apply:'Register',pay:'Payment',form:'Registration form',status:'Check status',open:'Registration open',closed:'Registration closed',fee:'Registration fee',unlimited:'Unlimited applicants',choose:'Choose category',payTitle:'Registration payment',payHelp:'Scan the PromptPay QR code and save the payment slip.',paid:'Payment completed • Continue',amount:'Amount',baht:'THB',applicant:'Applicant information',docType:'Document type',thaiId:'Thai National ID',passport:'Passport',first:'First name',last:'Last name',dob:'Date of birth',phone:'Phone',email:'Email',emergency:'Emergency contact',emergencyPhone:'Emergency phone',category:'Category',slip:'Payment slip',verifySlip:'Verify slip',checking:'Verifying payment slip...',verified:'Payment slip verified',submit:'Submit registration',terms:'I confirm the information is correct and accept the terms.',success:'Registration successful',waiting:'Saving registration...',required:'Please complete all required fields.',invalidThai:'Invalid Thai National ID.',invalidPassport:'Passport number format is invalid.',slipRequired:'Payment slip must be verified first.',back:'Back to home',lang:'Language'},
    zh:{home:'首页',apply:'报名',pay:'付款',form:'报名表',status:'查询状态',open:'报名开放',closed:'报名关闭',fee:'报名费',unlimited:'报名人数不限',choose:'选择比赛组别',payTitle:'支付报名费',payHelp:'扫描 PromptPay 二维码付款并保存付款凭证。',paid:'已付款 • 继续报名',amount:'金额',baht:'泰铢',applicant:'报名者信息',docType:'证件类型',thaiId:'泰国身份证',passport:'护照',first:'名字',last:'姓氏',dob:'出生日期',phone:'电话',email:'电子邮箱',emergency:'紧急联系人',emergencyPhone:'紧急联系电话',category:'比赛组别',slip:'付款凭证',verifySlip:'验证付款凭证',checking:'正在验证付款凭证...',verified:'付款凭证验证成功',submit:'提交报名',terms:'我确认资料正确并接受报名条款。',success:'报名成功',waiting:'正在保存报名资料...',required:'请填写所有必填项。',invalidThai:'泰国身份证号码无效。',invalidPassport:'护照号码格式无效。',slipRequired:'请先完成付款凭证验证。',back:'返回首页',lang:'语言'},
    ru:{home:'Главная',apply:'Регистрация',pay:'Оплата',form:'Форма регистрации',status:'Проверить статус',open:'Регистрация открыта',closed:'Регистрация закрыта',fee:'Регистрационный взнос',unlimited:'Без ограничения участников',choose:'Выберите категорию',payTitle:'Оплата регистрации',payHelp:'Отсканируйте PromptPay QR и сохраните чек.',paid:'Оплата завершена • Продолжить',amount:'Сумма',baht:'бат',applicant:'Данные участника',docType:'Тип документа',thaiId:'Тайский ID',passport:'Паспорт',first:'Имя',last:'Фамилия',dob:'Дата рождения',phone:'Телефон',email:'Email',emergency:'Экстренный контакт',emergencyPhone:'Телефон для экстренной связи',category:'Категория',slip:'Чек об оплате',verifySlip:'Проверить чек',checking:'Проверка чека...',verified:'Чек подтвержден',submit:'Отправить заявку',terms:'Я подтверждаю правильность данных и принимаю условия.',success:'Регистрация завершена',waiting:'Сохранение данных...',required:'Заполните обязательные поля.',invalidThai:'Неверный тайский ID.',invalidPassport:'Неверный формат паспорта.',slipRequired:'Сначала необходимо подтвердить чек.',back:'На главную',lang:'Язык'}
  };
  const supported=['th','en','zh','ru'];
  let lang=localStorage.getItem('top100_lang') || 'th'; if(!supported.includes(lang)) lang='th';
  function apply(){document.documentElement.lang=lang; document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(D[lang][k]!==undefined)el.textContent=D[lang][k];}); document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(D[lang][k]!==undefined)el.placeholder=D[lang][k];}); document.querySelectorAll('[data-lang-select]').forEach(s=>s.value=lang); window.dispatchEvent(new CustomEvent('languagechange',{detail:{lang}}));}
  window.I18N={get lang(){return lang}, t:k=>D[lang][k]||D.th[k]||k, set(v){if(supported.includes(v)){lang=v;localStorage.setItem('top100_lang',v);apply();}}, apply};
  document.addEventListener('change',e=>{if(e.target.matches('[data-lang-select]')) I18N.set(e.target.value)});
  document.addEventListener('DOMContentLoaded',apply);
})();
