(() => {
  const D={
    th:{home:'หน้าหลัก',apply:'สมัคร',pay:'ชำระเงิน',form:'ฟอร์มสมัคร',status:'ตรวจสอบสถานะ',open:'เปิดรับสมัคร',closed:'ปิดรับสมัคร',fee:'ค่าสมัคร',unlimited:'รับสมัครไม่จำกัดจำนวน',choose:'เลือกประเภทการแข่งขัน',payTitle:'ชำระค่าสมัคร',payHelp:'สแกน PromptPay QR Code แล้วบันทึกสลิปไว้',paid:'ชำระเงินแล้ว • ไปกรอกใบสมัคร',amount:'ยอดชำระ',baht:'บาท',applicant:'ข้อมูลผู้สมัคร',docType:'ประเภทเอกสาร',thaiId:'บัตรประชาชนไทย',passport:'Passport',first:'ชื่อ',last:'นามสกุล',dob:'วันเกิด',phone:'เบอร์โทรศัพท์',email:'อีเมล',emergency:'ผู้ติดต่อฉุกเฉิน',emergencyPhone:'เบอร์โทรฉุกเฉิน',category:'ประเภทการแข่งขัน',slip:'สลิปการชำระเงิน',verifySlip:'ตรวจสอบสลิป',checking:'กำลังตรวจ QR และตรวจสลิปซ้ำ...',verified:'คัดกรองสลิปผ่าน • รอ Admin ยืนยันเงินเข้า',submit:'ยืนยันการสมัคร',terms:'ยืนยันว่าข้อมูลถูกต้องและยอมรับเงื่อนไข',success:'สมัครสำเร็จ',waiting:'กำลังบันทึกข้อมูล...',savingTitle:'กำลังบันทึกการสมัคร...',savingHint:'กรุณารอสักครู่ อย่ากดปุ่มซ้ำ และอย่าปิดหน้านี้',approvalTitle:'สมัครเรียบร้อยแล้ว',approvalMessage:'ระบบบันทึกข้อมูลการสมัครเรียบร้อยแล้ว กรุณารอเจ้าหน้าที่ตรวจสอบและอนุมัติการสมัคร',approvalHint:'สามารถตรวจสอบสถานะภายหลังได้จากหน้าตรวจสอบรายชื่อ',ok:'ตกลง',required:'กรุณากรอกข้อมูลให้ครบ',invalidThai:'เลขบัตรประชาชนไม่ถูกต้อง',invalidPassport:'เลข Passport ไม่อยู่ในรูปแบบที่กำหนด',slipRequired:'ต้องตรวจสอบสลิปให้ผ่านก่อน',slipVerifyWarningTitle:'ยังไม่ได้ตรวจสอบสลิป',slipVerifyWarningMessage:'กรุณาเลือกสลิปและกดปุ่ม “ตรวจสอบสลิป” ให้ผ่านก่อนยืนยันการสมัคร',slipVerifyWarningConfirm:'ไปตรวจสอบสลิป',back:'กลับหน้าหลัก',lang:'ภาษา'},
    en:{home:'Home',apply:'Register',pay:'Payment',form:'Registration form',status:'Check status',open:'Registration open',closed:'Registration closed',fee:'Registration fee',unlimited:'Unlimited applicants',choose:'Choose category',payTitle:'Registration payment',payHelp:'Scan the PromptPay QR code and save the payment slip.',paid:'Payment completed • Continue',amount:'Amount',baht:'THB',applicant:'Applicant information',docType:'Document type',thaiId:'Thai National ID',passport:'Passport',first:'First name',last:'Last name',dob:'Date of birth',phone:'Phone',email:'Email',emergency:'Emergency contact',emergencyPhone:'Emergency phone',category:'Category',slip:'Payment slip',verifySlip:'Verify slip',checking:'Scanning slip QR and checking duplicates...',verified:'Slip screening passed • Awaiting Admin payment confirmation',submit:'Submit registration',terms:'I confirm the information is correct and accept the terms.',success:'Registration successful',waiting:'Saving registration...',savingTitle:'Saving your registration...',savingHint:'Please wait. Do not press the button again or close this page.',approvalTitle:'Registration submitted',approvalMessage:'Your registration has been saved successfully. Please wait for staff review and approval.',approvalHint:'You can check your status later on the registration check page.',ok:'OK',required:'Please complete all required fields.',invalidThai:'Invalid Thai National ID.',invalidPassport:'Passport number format is invalid.',slipRequired:'Payment slip must be verified first.',slipVerifyWarningTitle:'Payment slip not verified',slipVerifyWarningMessage:'Please select your payment slip and tap “Verify slip” successfully before submitting your registration.',slipVerifyWarningConfirm:'Verify slip',back:'Back to home',lang:'Language'},
    zh:{home:'首页',apply:'报名',pay:'付款',form:'报名表',status:'查询状态',open:'报名开放',closed:'报名关闭',fee:'报名费',unlimited:'报名人数不限',choose:'选择比赛组别',payTitle:'支付报名费',payHelp:'扫描 PromptPay 二维码付款并保存付款凭证。',paid:'已付款 • 继续报名',amount:'金额',baht:'泰铢',applicant:'报名者信息',docType:'证件类型',thaiId:'泰国身份证',passport:'护照',first:'名字',last:'姓氏',dob:'出生日期',phone:'电话',email:'电子邮箱',emergency:'紧急联系人',emergencyPhone:'紧急联系电话',category:'比赛组别',slip:'付款凭证',verifySlip:'验证付款凭证',checking:'正在扫描凭证二维码并检查重复...',verified:'付款凭证初步检查通过 • 等待管理员确认到账',submit:'提交报名',terms:'我确认资料正确并接受报名条款。',success:'报名成功',waiting:'正在保存报名资料...',savingTitle:'正在保存报名信息...',savingHint:'请稍候，请勿重复点击提交按钮或关闭此页面。',approvalTitle:'报名提交成功',approvalMessage:'系统已成功保存您的报名信息，请等待工作人员审核并批准。',approvalHint:'稍后可在报名查询页面查看审核状态。',ok:'确定',required:'请填写所有必填项。',invalidThai:'泰国身份证号码无效。',invalidPassport:'护照号码格式无效。',slipRequired:'请先完成付款凭证验证。',slipVerifyWarningTitle:'付款凭证尚未验证',slipVerifyWarningMessage:'请先选择付款凭证并点击“验证付款凭证”，验证通过后再提交报名。',slipVerifyWarningConfirm:'去验证付款凭证',back:'返回首页',lang:'语言'},
    ru:{home:'Главная',apply:'Регистрация',pay:'Оплата',form:'Форма регистрации',status:'Проверить статус',open:'Регистрация открыта',closed:'Регистрация закрыта',fee:'Регистрационный взнос',unlimited:'Без ограничения участников',choose:'Выберите категорию',payTitle:'Оплата регистрации',payHelp:'Отсканируйте PromptPay QR и сохраните чек.',paid:'Оплата завершена • Продолжить',amount:'Сумма',baht:'бат',applicant:'Данные участника',docType:'Тип документа',thaiId:'Тайский ID',passport:'Паспорт',first:'Имя',last:'Фамилия',dob:'Дата рождения',phone:'Телефон',email:'Email',emergency:'Экстренный контакт',emergencyPhone:'Телефон для экстренной связи',category:'Категория',slip:'Чек об оплате',verifySlip:'Проверить чек',checking:'Сканирование QR чека и проверка дубликатов...',verified:'Проверка чека пройдена • Ожидается подтверждение платежа администратором',submit:'Отправить заявку',terms:'Я подтверждаю правильность данных и принимаю условия.',success:'Регистрация завершена',waiting:'Сохранение данных...',savingTitle:'Сохраняем регистрацию...',savingHint:'Пожалуйста, подождите. Не нажимайте кнопку повторно и не закрывайте страницу.',approvalTitle:'Заявка отправлена',approvalMessage:'Регистрация успешно сохранена. Пожалуйста, дождитесь проверки и одобрения сотрудником.',approvalHint:'Позже статус можно проверить на странице проверки регистрации.',ok:'OK',required:'Заполните обязательные поля.',invalidThai:'Неверный тайский ID.',invalidPassport:'Неверный формат паспорта.',slipRequired:'Сначала необходимо подтвердить чек.',slipVerifyWarningTitle:'Чек еще не проверен',slipVerifyWarningMessage:'Выберите чек и успешно нажмите «Проверить чек» перед отправкой заявки.',slipVerifyWarningConfirm:'Проверить чек',back:'На главную',lang:'Язык'}
  };
  const supported=['th','en','zh','ru'];
  let lang=localStorage.getItem('top100_lang') || 'th'; if(!supported.includes(lang)) lang='th';
  function apply(){document.documentElement.lang=lang; document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(D[lang][k]!==undefined)el.textContent=D[lang][k];}); document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(D[lang][k]!==undefined)el.placeholder=D[lang][k];}); document.querySelectorAll('[data-lang-select]').forEach(s=>s.value=lang); window.dispatchEvent(new CustomEvent('languagechange',{detail:{lang}}));}
  window.I18N={get lang(){return lang}, t:k=>D[lang][k]||D.th[k]||k, set(v){if(supported.includes(v)){lang=v;localStorage.setItem('top100_lang',v);apply();}}, apply};
  document.addEventListener('change',e=>{if(e.target.matches('[data-lang-select]')) I18N.set(e.target.value)});
  document.addEventListener('DOMContentLoaded',apply);
})();
